### ISSUE TITLE
MainNet Preparation

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/harmony-ops#9]
This Issue keeps track of tasks that may be worked on in preparation for mainnet.

**Task List**
- [ ] Monitoring
  - [ ] mystatus.sh
  - [ ] uptimeRobot automatic scripting
- [ ] Documentation
  - [x] Create Harmony Wiki
    - [x] Status Page
   - [ ] Trouble Shooting Playbook
   - [x] Foundational Node Operators Guide
  -  [ ] Release Process
